### ISSUE TITLE
How do we create SQS?

### ISSUE THREAD

**Issue by tuananh1508** [Unee-T-INS/invite#4]
There some SQS in AWS(In the Unee-t dev) but we don't understand how and when these SQS are created.
https://console.aws.amazon.com/sqs/home?region=ap-southeast-1#

**Comment by kaihendry** [comment]
* "invites" is created manually, invites should be converted to a SAM structure, but I didn't get around to doing it
* lambda2sqs- is created via SAM template https://github.com/Unee-T-INS/lambda2sqs/blob/master/template.yaml

**Comment by kaihendry** [comment]
When it has a random string like this:

![image](https://user-images.githubusercontent.com/765871/72402135-30faa000-3789-11ea-8cd2-fb10eb696df8.png)


It's created by a SAM template

**Comment by kaihendry** [comment]
Manually
